# Generated by Django 3.2.13 on 2022-05-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220508_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='webste',
            new_name='website',
        ),
    ]
